
SELECT EXISTS(SELECT * FROM information_schema.tables 
    WHERE table_catalog = CURRENT_CATALOG 
    AND table_schema = CURRENT_SCHEMA
    AND table_name = 'aoc_day2_input') as table_exists;
\gset
\if :table_exists
    \echo 'Table already exists, quitting...'
    \q
\endif

CREATE TABLE aoc_day2_input (
    id integer GENERATED BY DEFAULT AS IDENTITY, -- needed for star 2
    direction varchar(7) NOT NULL,
    amount integer NOT NULL
);

\copy aoc_day2_input (direction, amount) from './input' (DELIMITER ' ');
